version: "3.1"

services:

  db:
    image: "postgres:14.1-alpine"
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456
    networks:
      - dbNet
    ports:
      - "15432:5432"

  adminer:
    image: "adminer"
    restart: always
    ports:
      - "8081:8080"
    networks:
      - dbNet

networks:
  dbNet:
    external: true