version: "3"

services:
  socat:
    image: "alpine/socat"
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "127.0.0.1:2376:2375"
    command: "tcp-listen:2375,fork,reuseaddr unix-connect:/var/run/docker.sock"

# docker run -d --restart=always \
#    -p 127.0.0.1:2376:2375 \
#    -v /var/run/docker.sock:/var/run/docker.sock \
#    alpine/socat \
#    tcp-listen:2375,fork,reuseaddr unix-connect:/var/run/docker.sock