apiVersion: apps/v1
kind: Deployment
metadata:
  name: tensor-serv
  namespace: tensor
  labels:
    app: tensor-serv

spec:
  replicas: 3
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: tensor-serv
  template:
    metadata:
      labels:
        app: tensor-serv
    spec:
      containers:
      - name: tensor-serv
        image: bitnami/tensorflow-serving:latest
        lifecycle:
          preStop:
            exec:
              command: ["sh","-c","sleep 5"]
        ports:
        - containerPort: 8080
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1024Mi
        volumeMounts:
        - name: timezone
          mountPath: /etc/localtime
      volumes:
        - name: timezone
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai

---

apiVersion: v1
kind: Service
metadata:
  name: tensor-serv-svc
  namespace: tensor
spec:
  ports:
    - port: 8080
  selector:
    app: tensor-serv

---

apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: tensor-serv-hpa-c
  namespace: tensor
  labels:
    app: tensor-serv-hpa-c
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tensor-serv
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 80

---

apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: tensor-serv-hpa-m
  namespace: tensor
  labels:
    app: tensor-serv-hpa-m
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tensor-serv
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 80
